#!/usr/bin/env bash
# fetch-abis.sh
# Corre desde la raíz del proyecto: bash fetch-abis.sh
#
# Genera:
#   src/contracts/abis.ts
#   src/contracts/addresses.ts
#   src/lib/contracts-abi.ts   

set -euo pipefail

API_KEY="EVYAB3P2235JGZ4WHPCCZQYS4B8UUPI143"
CHAIN_ID="421614"  # Arbitrum Sepolia
BASE_URL="https://api.etherscan.io/v2/api?chainid=${CHAIN_ID}&module=contract&action=getabi&apikey=${API_KEY}"

NAMES=(
  DATETIME
  TREASURY
  PROTOCOL_REGISTRY
  TOKEN
  GOVERNANCE
  USER_PREFERENCES
  PERSONAL_FUND
  PERSONAL_FUND_FACTORY
)

ADDRS=(
  "0xeb91ef08F65b6BFE4753db429e8d82A28a1970c5"
  "0x045F8Ff2387813778DBc9ce93677669891a92909"
  "0xb215948f03959F61d0ca918f02F1d0789Af8a0BC"
  "0x853B2e3D6e26183DDDedA90A45Ff3C639873899c"
  "0x28E37450297593B621eecD1Ad069D2748354184E"
  "0x1ed2B6bD2124D322c42985a072DB6751634DDCFF"
  "0x078d0457165c85bf566FB4E8511F1CFa64674f92"
  "0x8101f50Abef13511eAbA87469A51B5106A54CA92"
)

mkdir -p src/contracts src/lib
TMP_DIR=$(mktemp -d)
trap 'rm -rf "$TMP_DIR"' EXIT

echo "Fetching ABIs — Etherscan V2 (chainid=${CHAIN_ID})..."
echo ""

for i in "${!NAMES[@]}"; do
  NAME="${NAMES[$i]}"
  ADDR="${ADDRS[$i]}"

  RESPONSE=$(curl -s "${BASE_URL}&address=${ADDR}")
  STATUS=$(echo "$RESPONSE" | python3 -c "import sys,json; print(json.load(sys.stdin).get('status','0'))")

  if [ "$STATUS" = "1" ]; then
    echo "$RESPONSE" | python3 -c "import sys,json; print(json.load(sys.stdin)['result'])" \
      > "${TMP_DIR}/${NAME}.json"
    echo "  ✓  ${NAME}"
  else
    MSG=$(echo "$RESPONSE" | python3 -c "import sys,json; d=json.load(sys.stdin); print(d.get('result') or d.get('message','unknown error'))")
    echo "  ✗  ${NAME}: ${MSG}"
    exit 1
  fi

  sleep 0.25
done

echo ""
echo "Generando archivos TypeScript..."

ABI_FILE="src/contracts/abis.ts"
cat > "$ABI_FILE" << 'HEADER'
// Auto-generated by fetch-abis.sh — do not edit manually
// Chain: Arbitrum Sepolia (421614)
// Source: Etherscan V2 API

HEADER

for NAME in "${NAMES[@]}"; do
  ABI_JSON=$(cat "${TMP_DIR}/${NAME}.json")
  PRETTY=$(echo "$ABI_JSON" | python3 -c "import sys,json; print(json.dumps(json.loads(sys.stdin.read()), indent=2))")
  printf 'export const %s_ABI = %s as const;\n\n' "$NAME" "$PRETTY" >> "$ABI_FILE"
done

echo "  → $ABI_FILE"
ADDR_FILE="src/contracts/addresses.ts"
cat > "$ADDR_FILE" << 'HEADER'
// Auto-generated by fetch-abis.sh — do not edit manually
// Chain: Arbitrum Sepolia (421614)

export const CONTRACT_ADDRESSES = {
HEADER

for i in "${!NAMES[@]}"; do
  NAME="${NAMES[$i]}"
  ADDR="${ADDRS[$i]}"
  printf '  %s: '"'"'%s'"'"' as `0x${string}`,\n' "$NAME" "$ADDR" >> "$ADDR_FILE"
done

cat >> "$ADDR_FILE" << 'FOOTER'
} as const;

// Named exports — coinciden con las VITE_ env vars
export const TREASURY_ADDRESS              = CONTRACT_ADDRESSES.TREASURY;
export const PERSONAL_FUND_FACTORY_ADDRESS = CONTRACT_ADDRESSES.PERSONAL_FUND_FACTORY;
export const PERSONAL_FUND_ADDRESS         = CONTRACT_ADDRESSES.PERSONAL_FUND;
export const GOVERNANCE_ADDRESS            = CONTRACT_ADDRESSES.GOVERNANCE;
export const TOKEN_ADDRESS                 = CONTRACT_ADDRESSES.TOKEN;
export const PROTOCOL_REGISTRY_ADDRESS     = CONTRACT_ADDRESSES.PROTOCOL_REGISTRY;
export const USER_PREFERENCES_ADDRESS      = CONTRACT_ADDRESSES.USER_PREFERENCES;
export const DATETIME_ADDRESS              = CONTRACT_ADDRESSES.DATETIME;
FOOTER

echo "  → $ADDR_FILE"
cat > "src/lib/contracts-abi.ts" << 'EOF'
// Re-export shim — mantiene los imports existentes funcionando
// Fuente canónica: src/contracts/abis.ts

export {
  DATETIME_ABI,
  TREASURY_ABI,
  PROTOCOL_REGISTRY_ABI,
  TOKEN_ABI,
  GOVERNANCE_ABI,
  USER_PREFERENCES_ABI,
  PERSONAL_FUND_ABI,
  PERSONAL_FUND_FACTORY_ABI,
} from '@/contracts/abis';
EOF

echo "  → src/lib/contracts-abi.ts"

echo ""
echo "Done ✓"